name: github-action-test
run-name: Github Action
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
jobs:
  build_fe:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./02_WEB
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
    - run: npm i
    - run: npm run build
    - run: robocopy .\dist Source\02_WEB\dist /E /XF web.config; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null }
